#+TITLE: Gestión de de la información de usuarios registrados en la UPR
#+AUTHOR: Luis Ángel Méndez Gort
#+EMAIL: gort.andres000@gmail.com
#+LATEX_CLASS: article
#+OPTIONS: toc:nil

* Introducción

En la UPR el Directorio de Informatización se ocupa de 
mantener todas las redes de computadoras. Ellos mantienen y
expanden la infraestructura de hardware y software. Actualmente
todos los servicios son usados por usuarios registrados

Este programa surge de la necesidad de sincronizar los usuarios
de las bases de datos SIGENU y ASET, con el directorio activo
(el servidor LDAP accesible a través de la dirección ad.upr.edu.cu,
que se usa directamente para autenticar los usuarios).

Este servicio será usado por quienes estén en determinado grupo
del AD creado con el propósito de agrupar esos usuarios.

El proceso de sicronización consiste en agregar en el ad
los campos de usuario que esten en las bases de datos y
que aún no existan en él.

* Design
#+BEGIN_SRC
proc serveUser |[
  auth
  ;dash
]|

proc serve |[
  *[serve]
]|
#+END_SRC

#+BEGIN_SRC
proc auth |[
  
]|

a ≢ b ∧ (a ∨ b) ≡ a ∨ b
#+END_SRC
