#+TITLE: Network services portal of the University of Pinar del Río
#+AUTHOR: Luis Ángel Méndez Gort
#+EMAIL: gort.andres000@gmail.com
#+LATEX_CLASS: article
#+OPTIONS: toc:nil

* Introduction

At University of Pinar del Río (UPR), the Directorate of
Computerization (DC) is the department in charge of all aspects of the
computer networks. They maintain and expand the hardware and software
infrastructure. Currently all services are used by registered users.

This program comes from the following necessities of UPR's DC:

- Register the MAC and IP addresses used to access the users accounts,
  and use that information for reporting the account access to users
  and administrators.

- Place consumption of the different quotas, like the email storage
  quota and the internet download quota, in a single site.

- Automate the delivery of contracts for using the network services,
  using the network itself.

- Notify the users, thus avoiding the impersonation of administrators
  which is common with the current email notifications, and also the
  duplication of messages in mailboxes.

- Document the implemented services.

* Implementation

In this section every previous necessity will be satisfied by the
implementation of the corresponding feature.

** Feature 0

Register the MAC and IP addresses used to access the users accounts,
and use that information for reporting the account access to users and
administrators.

This operation consists in two separate steps: register the MAC and
the IP when an user logs in, and report to an user or to an
administrator the information about access they are allowed to see.

Along this document Haskell is used as specification language, the
following functions express the previous paragraph's statements:

#+BEGIN_SRC haskell
#+END_SRC

** TODO
