#+TITLE: Network services portal of the University of Pinar del Río
#+AUTHOR: Luis Ángel Méndez Gort
#+EMAIL: gort.andres000@gmail.com
#+LATEX_CLASS: article
#+OPTIONS: toc:nil

* Introduction

At University of Pinar del Río (UPR), the Directorate of
Computerization (DC) is the department in charge of all aspects of the
computer networks. They maintain and expand the hardware and software
infrastructure. Currently all services are used by registered users.

This program comes from the following necessities of UPR's DC:

- Register the MAC and IP addresses used to access the users accounts,
  and use that information for reporting the account access to users
  and administrators.

- Place consumption of the different quotas, like the email storage
  quota and the internet download quota, in a single site.

- Automate the delivery of contracts for using the network services,
  using the network itself.

- Notify the users, thus avoiding the impersonation of administrators
  which is common with the current email notifications, and also the
  duplication of messages in mailboxes.

- Document the implemented services.

But in general perspective, all these services are instances of an
interface for receiving messages and content regarding certain fixed
subjects, which are the services implemented at UPR's network.

* Implementation

_REMARK_ Along this document Haskell is used as specification
language. _END OF REMARK_

